[
    "https:\/\/cdn.troke.id\/seasonal\/1.jpg",
    "https:\/\/cdn.troke.id\/seasonal\/2.jpg",
    "https:\/\/cdn.troke.id\/seasonal\/3.jpg",
    "https:\/\/cdn.troke.id\/seasonal\/4.jpg",
    "https:\/\/cdn.troke.id\/seasonal\/5.jpg",
    "https:\/\/cdn.troke.id\/seasonal\/6.jpg",
    "https:\/\/cdn.troke.id\/seasonal\/7.jpg"
]
